const t={zh:{'nav.home':'首页','nav.video':'视频介绍','nav.about':'关于我','nav.work':'展示','nav.insight':'分析','nav.contact':'联系分享','hero.eyebrow':'视觉表达者 / 全球化探索者','hero.title':'用设计的感知，<br>连接更大的世界。','hero.summary':'视觉传达设计背景，正在把理解用户、清晰表达和行动力，带进销售、跨文化沟通与出海探索中。','hero.cta':'查看我的作品','hero.scroll':'向下探索 ↓','placeholder.photo':'个人照片<br>待替换','video.label':'视频介绍','video.copy':'这是一段关于我如何从设计走向商业与全球化领域的自我介绍。内容与脚本将随视频完成后补充。','video.cta':'观看视频介绍','placeholder.video':'视频封面 / PNG 人像<br>待替换','about.label':'关于我','about.lead':'我更希望在这里呈现一个立体的人：我如何观察、协作、创造，也如何在新场景中快速行动。','placeholder.life1':'生活或活动照片','placeholder.life2':'团队协作照片','about.note1':'观察','about.note2':'行动','about.profile':'好奇心是<br>我的起点。','about.profilecopy':'设计训练我看见细节；真实项目让我更愿意走进人群。','about.trait1':'敏锐的观察者','about.trait1p':'习惯从受众、场景和情绪中寻找表达与沟通的入口。','about.trait2':'可靠的协作者','about.trait2p':'在团队里承担衔接、推进和把事情落到实处的角色。','about.trait3':'持续的探索者','about.trait3p':'对跨文化、人、商业与新鲜事物始终保有好奇。','work.label':'成果展示','work.title':'成果展示<span>.</span>','work.lead':'每一个项目都可以展开成一段完整的过程：情境、行动、图片、数据与结果。','filter.all':'全部','filter.sales':'销售 & BD','filter.global':'跨文化沟通','filter.design':'设计案例','case.youdao':'把一次沟通，推进成一份信任。','case.bd':'走进市场，也走进客户的现场。','case.f1':'让跨语言协作，始终保持顺畅。','case.design':'把想法做成可以被看见的表达。','insight.label':'出海行业洞察','insight.title':'出海相关<br>作品集。','insight.lead':'一个以行业洞察为起点的作品集模板。后续可替换为你研究的具体行业、资料与图表。','insight.boardtitle':'K-POP 卖的不是周边，而是情绪链路','insight.summary':'人们购买的并不只是产品，而是参与感、身份认同，以及与社群共同经历的某个时刻。','insight.step1':'情绪预告','insight.step2':'概念释出','insight.step3':'专辑配置','insight.step4':'签售机制','insight.step5':'社媒内容','insight.step6':'复盘','insight.point1':'行业动机','insight.point1p':'先识别用户为什么愿意靠近这个行业与品牌。','insight.point2':'用户价值','insight.point2p':'产品功能之外，用户真正获得的体验与关系是什么？','insight.point3':'情绪与身份','insight.point3p':'用内容与机制让用户愿意表达、留下并分享。','insight.note':'此处预留：行业数据、用户访谈、竞品案例与个人策略图。','tools.label':'工具分享','tools.title':'工具分享<br><span>与持续学习。</span>','tools.one':'查看 / 下载简历','tools.two':'我的工具与资源清单','tools.three':'文章与行业观察','contact.title':'期待与你','contact.hand':'connect.','contact.copy':'欢迎与我聊聊机会、项目和那些还没有被想到的可能。','footer.top':'回到顶部 ↑','dialog.video':'视频素材上传后，将在这里播放。'},en:{'nav.home':'HOME','nav.video':'VIDEO','nav.about':'ABOUT','nav.work':'WORK','nav.insight':'INSIGHT','nav.contact':'CONTACT','hero.eyebrow':'VISUAL THINKER / GLOBAL EXPLORER','hero.title':'DESIGNING CONNECTIONS<br>FOR A BIGGER WORLD.','hero.summary':'A visual communication designer bringing audience empathy, clear storytelling, and action into sales, cross-cultural collaboration, and global exploration.','hero.cta':'EXPLORE MY WORK','hero.scroll':'SCROLL TO EXPLORE ↓','placeholder.photo':'PORTRAIT<br>TO BE ADDED','video.label':'VIDEO INTRODUCTION','video.copy':'A short introduction to my path from design to business and global work. The final script and film will be added here.','video.cta':'WATCH INTRO VIDEO','placeholder.video':'VIDEO COVER / PNG PORTRAIT<br>TO BE ADDED','about.label':'ABOUT ME','about.lead':'This is the person behind the work: how I observe, collaborate, create, and make progress in new situations.','placeholder.life1':'LIFE / ACTIVITY PHOTO','placeholder.life2':'TEAMWORK PHOTO','about.note1':'OBSERVE','about.note2':'ACT','about.profile':'CURIOSITY<br>STARTS IT ALL.','about.profilecopy':'Design taught me to notice details. Real projects taught me to move closer to people.','about.trait1':'A sharp observer','about.trait1p':'I look for human context, emotion, and moments that make communication meaningful.','about.trait2':'A dependable collaborator','about.trait2p':'I connect people, move work forward, and turn loose ends into action.','about.trait3':'A constant explorer','about.trait3p':'I stay curious about people, culture, business, and what is next.','work.label':'SELECTED WORK','work.title':'SELECTED WORK<span>.</span>','work.lead':'Every project opens into a complete story: context, action, visuals, data, and outcomes.','filter.all':'ALL','filter.sales':'SALES & BD','filter.global':'CROSS-CULTURAL','filter.design':'DESIGN','case.youdao':'Turning a conversation into trust.','case.bd':'Going into the market, and into the client’s world.','case.f1':'Keeping cross-language collaboration flowing.','case.design':'Making ideas visible and tangible.','insight.label':'GLOBAL MARKET INSIGHT','insight.title':'GLOBAL<br>CASE NOTES.','insight.lead':'A portfolio template that begins with industry insight. Replace it with your researched industry, sources, and charts.','insight.boardtitle':'K-POP SELLS AN EMOTIONAL JOURNEY, NOT JUST MERCH','insight.summary':'What people buy is participation, identity, and a moment shared with their community.','insight.step1':'TEASER','insight.step2':'CONCEPT','insight.step3':'ALBUM','insight.step4':'FANSIGN','insight.step5':'SOCIAL','insight.step6':'RECAP','insight.point1':'INDUSTRY MOTIVE','insight.point1p':'Find out why people are drawn to this world in the first place.','insight.point2':'USER VALUE','insight.point2p':'Beyond function, what experience and relationship does a user gain?','insight.point3':'EMOTION & IDENTITY','insight.point3p':'Create content and systems people want to express, keep, and share.','insight.note':'Reserved for: market data, user interviews, competitors, and your strategy map.','tools.label':'TOOLS & SHARING','tools.title':'TOOLS, NOTES<br><span>&amp; LEARNING.</span>','tools.one':'VIEW / DOWNLOAD RÉSUMÉ','tools.two':'TOOLS & RESOURCES','tools.three':'NOTES & OBSERVATIONS','contact.title':'LET’S','contact.hand':'connect.','contact.copy':'Let’s talk opportunities, projects, and possibilities not yet imagined.','footer.top':'BACK TO TOP ↑','dialog.video':'Your introduction film will play here once it is uploaded.'}};
function setLanguage(lang){if(t[lang]['page.title'])document.title=t[lang]['page.title'];if(t[lang]['page.description'])document.querySelector('meta[name="description"]').content=t[lang]['page.description'];document.documentElement.lang=lang==='zh'?'zh-CN':'en';document.querySelectorAll('[data-i18n]').forEach(e=>e.innerHTML=t[lang][e.dataset.i18n]||e.innerHTML);document.querySelectorAll('.language').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));localStorage.setItem('portfolio-language',lang)}document.querySelectorAll('.language').forEach(b=>b.addEventListener('click',()=>setLanguage(b.dataset.lang)));setLanguage(localStorage.getItem('portfolio-language')||'zh');
const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('#navigation');toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false')}));document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.case-card').forEach(c=>c.hidden=b.dataset.filter!=='all'&&c.dataset.category!==b.dataset.filter)}));const dialog=document.querySelector('#video-dialog');document.querySelectorAll('.video-trigger').forEach(x=>x.addEventListener('click',e=>{e.preventDefault();dialog.showModal()}));document.querySelector('.close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});

Object.assign(t.zh,{
  'page.title':'荆涵博｜海外销售助理求职作品集',
  'page.description':'荆涵博，2027届本科生，求职海外销售助理实习。展示销售实践、商户开发、国际赛事英语沟通及海外业务模拟案例。',
  'contact.title':'期待与您',
  'contact.hand':'Contact.',
  'contact.copy':'欢迎与我聊聊海外销售实习与团队机会。',
  'contact.email':'邮箱：',
  'contact.phone':'电话：',
  'contact.direction.title':'希望从海外销售助理做起',
  'contact.direction.body':'销售实践与国际赛事中的英语沟通，让我逐渐明确了向海外销售发展的方向。我希望从产品学习、客户资料搜集、沟通支持与业务跟进做起，认真承担具体工作，在实践中逐步提升客户开发能力。',
  'contact.interview.title':'期待一次进一步交流的机会',
  'contact.interview.body':'如果贵团队正在招聘海外销售助理或相关实习生，我很期待获得面试机会，进一步介绍我的经历，并了解团队的业务与要求。我愿意配合面试安排，尽快前往线下面谈。感谢您花时间了解我，期待有机会加入团队，在实际工作中贡献所长、继续学习。',
  'case.local.title':'本地生活商户开发',
  'case.local.subtitle':'电话触达 · 到店演示 · 合作推进',
  'case.local.credit':'服务方宣传资料',
  'case.local.category':'创业实践 / 商户开发与销售',
  'case.local.summary':'主动寻找商户，把沟通推进到合作。',
  'case.local.tags':'客户筛选 · 微信跟进 · 售后协作',
  'hero.eyebrow':'GLOBAL SALES ·<br>COMMUNICATION · EXECUTION',
  'hero.title':'理解需求，表达价值，<br>让沟通走向成交。',
  'hero.summary':'视觉传达背景，销售实践经历。擅长从客户视角理解需求、清晰表达价值并持续推进沟通。希望将国内销售与主动拓客经验应用于海外业务。',
  'hero.job':'2027届本科｜求职方向：海外销售实习 / 海外业务助理<br>意向城市：深圳优先，广州亦可<br>可连续实习至少3个月｜每周5天｜可长期实习｜录用确认后3天内到岗',
  'hero.resume':'下载简历',
  'case.youdao.result':'2025年12月小组销冠｜当月销售额8.5万元以上',
  'case.youdao.conversion':'各期购课转化率约9%—15%',
  'case.f1.cover.title':'F1H2O国际赛事｜<wbr>阿拉伯车队接待与英语沟通',
  'case.f1.cover.subtitle':'突出贡献志愿者｜参与车队接待、双向英语沟通与赛事现场支持',
  'case.f1.category':'阿拉伯车队接待与沟通 / F1H2O',
  'case.f1':'用英语连接车队与中方工作人员，配合完成赛事现场安排。'
});
Object.assign(t.en,{
  'page.title':'Jing Hanbo | Overseas Sales Assistant Job Portfolio',
  'page.description':'Jing Hanbo, a bachelor’s student graduating in 2027, seeking an overseas sales assistant internship. A portfolio of sales practice, merchant development, English communication at an international sporting event, and a simulated overseas business case.',
  'contact.title':'Let’s talk',
  'contact.hand':'Contact.',
  'contact.copy':'I welcome a conversation about overseas sales internships and opportunities with your team.',
  'contact.email':'Email:',
  'contact.phone':'Phone:',
  'contact.direction.title':'Starting as an overseas sales assistant',
  'contact.direction.body':'Sales practice and English communication at an international sporting event have helped clarify my direction toward overseas sales. I hope to start with product learning, customer research, communication support and business follow-up, taking responsibility for concrete tasks and gradually developing my client acquisition skills through practice.',
  'contact.interview.title':'An opportunity to talk further',
  'contact.interview.body':'If your team is recruiting an overseas sales assistant or an intern in a related role, I would welcome an interview to share more about my experience and learn about your business and requirements. I am willing to accommodate interview arrangements and travel promptly for an in-person meeting. Thank you for taking the time to get to know me. I hope to join a team where I can contribute my strengths and continue learning through practical work.',
  'case.local.title':'Local Merchant Development',
  'case.local.subtitle':'Phone outreach · On-site demos · Partnership development',
  'case.local.credit':'Service provider’s promotional material',
  'case.local.category':'Entrepreneurial Practice / Merchant Development & Sales',
  'case.local.summary':'Proactively finding merchants and turning conversations into partnerships.',
  'case.local.tags':'Prospect screening · WeChat follow-up · After-sales support',
  'hero.eyebrow':'GLOBAL SALES ·<br>COMMUNICATION · EXECUTION',
  'hero.title':'UNDERSTAND NEEDS.<br>COMMUNICATE VALUE.',
  'hero.summary':'With a background in visual communication and hands-on sales experience, I understand needs from the client’s perspective, communicate value clearly, and move conversations forward. I hope to apply my domestic sales and proactive prospecting experience to overseas business.',
  'hero.job':'Bachelor’s student, Class of 2027 | Seeking an overseas sales internship / overseas business assistant role<br>Preferred locations: Shenzhen first; Guangzhou also welcome<br>Available for at least 3 consecutive months | 5 days per week | Available for a long-term internship | Can start within 3 days after the offer is confirmed',
  'hero.resume':'Download résumé',
  'case.youdao.result':'December 2025 team sales champion | Monthly sales above RMB 85,000',
  'case.youdao.conversion':'Approx. 9%–15% course purchase conversion per cohort',
  'case.f1.cover.title':'F1H2O | Arab Team Reception & English Communication',
  'case.f1.cover.subtitle':'Outstanding Contribution Volunteer | Team reception, two-way English communication and on-site support',
  'case.f1.category':'Arab Team Reception & Communication / F1H2O',
  'case.f1':'Connected the Arab team and Chinese staff in English to support on-site arrangements.'
});
setLanguage(localStorage.getItem('portfolio-language')||'zh');
